src/objects/LittleBitsTrigger__c.object
<CustomObject>
    <fields>
        <fullName>AccessToken__c</fullName>
        <inlineHelpText>Optional, if the LittleBits API Custom Setting is configured.</inlineHelpText>
        <label>Access Token</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DeviceID__c</fullName>
        <inlineHelpText>Optional, if the LittleBits API Custom Setting is configured.</inlineHelpText>
        <label>Device ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DurationInMillisecondsField__c</fullName>
        <label>Duration in Milliseconds Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DurationInMilliseconds__c</fullName>
        <label>Duration in Milliseconds</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PercentField__c</fullName>
        <label>Percent Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>RecordID__c</fullName>
        <label>Record ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WhenFieldsModified__c</fullName>
        <inlineHelpText>A list of fields, separated by a comma, that will cause the trigger to fire if modified.</inlineHelpText>
        <label>When Fields Modified</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LittleBits Record Trigger</label>
    <nameField>
        <label>LittleBits Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LittleBits Record Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LittleBitsTriggerSelector.cls
/**
 * Copyright (c), Andrew Fawcett, inc
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, 
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, 
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, 
 *      this list of conditions and the following disclaimer in the documentation 
 *      and/or other materials provided with the distribution.
 * - Neither the name of the Andrew Fawcett, inc nor the names of its contributors 
 *      may be used to endorse or promote products derived from this software without 
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/

/**
 * Class encapsulates query logic for LittleBitsTrigger__c
 *
 * https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Selector_Layer
 **/
public class LittleBitsTriggerSelector extends fflib_SObjectSelector
	implements ILittleBitsTriggerSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
				LittleBitsTrigger__c.Id,
				LittleBitsTrigger__c.AccessToken__c,
				LittleBitsTrigger__c.Active__c,
				LittleBitsTrigger__c.DeviceID__c,
				LittleBitsTrigger__c.DurationInMilliseconds__c,
				LittleBitsTrigger__c.DurationInMillisecondsField__c,
				LittleBitsTrigger__c.Percent__c,
				LittleBitsTrigger__c.PercentField__c,
				LittleBitsTrigger__c.RecordID__c,
				LittleBitsTrigger__c.WhenFieldsModified__c
			};
	}

	public Schema.SObjectType getSObjectType()
	{
		return LittleBitsTrigger__c.sObjectType;
	}

	public List<LittleBitsTrigger__c> selectById(Set<ID> idSet)
	{
		return (List<LittleBitsTrigger__c>) selectSObjectsById(idSet);
	}

	public List<LittleBitsTrigger__c> selectActiveByRecordId(Set<Id> idSet) 
	{
		return (List<LittleBitsTrigger__c>)
			Database.query(
				newQueryFactory().setCondition('Active__c = true And RecordID__c in :idSet').toSOQL());
	}
}