src/objects/LittleBitsDeviceSubscription__c.object
<CustomObject>
    <fields>
        <fullName>AccessToken__c</fullName>
        <inlineHelpText>Optional, if the LittleBits API Custom Setting is configured.</inlineHelpText>
        <label>Access Token</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DeviceID__c</fullName>
        <label>Device ID</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <inlineHelpText>Manage the subscriptions with the device by clicking the Manage button.</inlineHelpText>
        <label>Event</label>
        <picklist>
            <picklistValues>
                <fullName>amplitude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>amplitude:delta:sustain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>amplitude:delta:ignite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>amplitude:delta:release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>amplitude:delta:nap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>amplitude:level:active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>amplitude:level:idle</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>FlowName__c</fullName>
        <inlineHelpText>Name of the Automation Flow to call when the Device events fire. Declare zero or more of the following input variables in the Flow. lbc_subscriptionRecordId, lbc_type, lbc_timestamp, lbc_user_id, lbc_bit_id, lbc_payload_percent or lbc_payload_delta</inlineHelpText>
        <label>Flow Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>LittleBits Device Subscription</label>
    <nameField>
        <label>LittleBits Subscriptions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LittleBits Device Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LittleBitsDeviceSubscriptionsSelector.cls
/**
 * Copyright (c), Andrew Fawcett, inc
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, 
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, 
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, 
 *      this list of conditions and the following disclaimer in the documentation 
 *      and/or other materials provided with the distribution.
 * - Neither the name of the Andrew Fawcett, inc nor the names of its contributors 
 *      may be used to endorse or promote products derived from this software without 
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/

/**
 * Class encapsulates query logic for LittleBitsDeviceSubscription__c
 *
 * https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Selector_Layer
 **/
public class LittleBitsDeviceSubscriptionsSelector extends fflib_SObjectSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
				LittleBitsDeviceSubscription__c.Id,
				LittleBitsDeviceSubscription__c.Active__c,
				LittleBitsDeviceSubscription__c.DeviceID__c,
				LittleBitsDeviceSubscription__c.AccessToken__c,
				LittleBitsDeviceSubscription__c.Event__c,
				LittleBitsDeviceSubscription__c.FlowName__c
			};
	}

	public Schema.SObjectType getSObjectType()
	{
		return LittleBitsDeviceSubscription__c.sObjectType;
	}

	public List<LittleBitsDeviceSubscription__c> selectById(Set<ID> idSet)
	{
		return (List<LittleBitsDeviceSubscription__c>) selectSObjectsById(idSet);
	}

	public List<LittleBitsDeviceSubscription__c> getAllActiveByDeviceId(Set<String> deviceIds) {
		return Database.query(
			newQueryFactory().setCondition('Active__c = true AND DeviceId__c in :deviceIds').toSOQL());
	}	
}